on: [push]
name: CI-CD Bicep Demo
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: script
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group list

    #   # Deploy Bicep file
    # - name: deploy
    #   uses: azure/arm-deploy@v1
    #   with:
    #     scope: subscription
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     template: ./Bicep/4.CI-CD/main.bicep
    #     failOnStdErr: false