# set workflow to manual
on: [workflow_dispatch]

name: CI-CD Bicep Demo linter
jobs:
  verifyDeploy:
    name: verify bicep code
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # validate bicep code
    - uses: azure/CLI@v1
      name: validate bicep files using linter spec
      with:
        inlineScript: |
          az bicep build --file $GITHUB_WORKSPACE/Bicep/4.CI-CD/main.bicep
  
  deploy:
    name: deploy infra
    runs-on: ubuntu-latest
    needs: [verifyDeploy] # depend on verify job
    steps:
      
      # Checkout code
    - uses: actions/checkout@main

      
      # azure login
    - uses: azure/login@v1
      name: 'Logging in to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # set as secret JSON object in repo

      # Deploy Bicep file
    - name: deploy bicep file
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: westeurope # we need to set this on subscription scoped deployments
        template: ./Bicep/4.CI-CD/main.bicep
        parameters: env=prod databaseName=cicd serverLogin=${{ secrets.BICEPDEMO_DBLOGIN_NAME }} serverLoginId=${{ secrets.BICEPDEMO_DBLOGIN_ID }}
        failOnStdErr: false
        showRawStdOut: true