# set workflow to manual trigger
on: [workflow_dispatch]

name: CI-CD Bicep Demo
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      name: 'Logging in to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # set as secret JSON object in repo

      # Deploy Bicep file
    - name: deploy bicep file
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: westeurope # we need to set this on subscription scoped deployments
        template: ./Bicep/4.CI-CD/main.bicep
        parameters: env=prod databaseName=cicd serverLogin=${{ secrets.BICEPDEMO_DBLOGIN_NAME }} serverLoginId=${{ secrets.BICEPDEMO_DBLOGIN_ID }}
        failOnStdErr: false